export default {
  nodes: [
    { name: "Salaried Employment", color: "#E8B0D1" },
    { name: "Informal Work", color: "#32DCE3"  },
    { name: "Own Business", color: "#ECDC8F"  },
    { name: "Agricultural Production or Labor", color: "#01CA97"  },
    { name: "Originally Unemployed", color: "#F4AD6A"  },
    { name: "Domestic Work", color: "#4997D0"  },
    { name: "Unpaid Home Care", color: "#67923D"  },
    { name: "Salaried Employment", color: "#E8B0D1"  },
    { name: "Informal Work", color: "#32DCE3"  },
    { name: "Own Business", color: "#ECDC8F"  },
    { name: "Agricultural Production or Labor", color: "#01CA97"  },
    { name: "Originally Unemployed", color: "#F4AD6A"  },
    { name: "Domestic Work", color: "#4997D0"  },
    { name: "Unpaid Home Care", color: "#67923D"  },
  ],
  links: [
    { source: 0, target: 7, value: 139 },
    { source: 0, target: 8, value: 30 },
    { source: 0, target: 9, value: 9 },
    { source: 0, target: 10, value: 9 },
    { source: 0, target: 11, value: 9 },
    { source: 0, target: 12, value: 12 },
    { source: 0, target: 13, value: 4 },
    { source: 1, target: 7, value: 39 },
    { source: 1, target: 8, value: 209 },
    { source: 1, target: 9, value: 23 },
    { source: 1, target: 10, value: 15 },
    { source: 1, target: 11, value: 11 },
    { source: 1, target: 12, value: 2 },
    { source: 1, target: 13, value: 12 },
    { source: 2, target: 7, value: 7 },
    { source: 2, target: 8, value: 13 },
    { source: 2, target: 9, value: 51 },
    { source: 2, target: 10, value: 3 },
    { source: 2, target: 11, value: 0 },
    { source: 2, target: 12, value: 1 },
    { source: 2, target: 13, value: 6 },
    { source: 3, target: 7, value: 40 },
    { source: 3, target: 8, value: 78 },
    { source: 3, target: 9, value: 11 },
    { source: 3, target: 10, value: 239 },
    { source: 3, target: 11, value: 20 },
    { source: 3, target: 12, value: 4 },
    { source: 3, target: 13, value: 3 },
    { source: 4, target: 7, value: 22 },
    { source: 4, target: 8, value: 26 },
    { source: 4, target: 9, value: 2 },
    { source: 4, target: 10, value: 4 },
    { source: 4, target: 11, value: 23 },
    { source: 4, target: 12, value: 7 },
    { source: 4, target: 13, value: 4 },
    { source: 5, target: 7, value: 5 },
    { source: 5, target: 8, value: 1 },
    { source: 5, target: 9, value: 2 },
    { source: 5, target: 10, value: 2 },
    { source: 5, target: 11, value: 0 },
    { source: 5, target: 12, value: 35 },
    { source: 5, target: 13, value: 5 },
    { source: 6, target: 7, value: 8 },
    { source: 6, target: 8, value: 11 },
    { source: 6, target: 9, value: 4 },
    { source: 6, target: 10, value: 3 },
    { source: 6, target: 11, value: 3 },
    { source: 6, target: 12, value: 3 },
    { source: 6, target: 13, value: 61 },
  ],
};




